name: ðŸš€ Test and Deploy

on:
  push:
    branches:
      - release/1.0
      - development
      - main
  workflow_dispatch:

permissions:
  issues: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI/CD Repo
        uses: actions/checkout@v3

      - name: Checkout Java App Repo
        uses: actions/checkout@v3
        with:
          repository: ManojAndroid/Social-Service
          ref: main                # âœ… explicitly mention the branch
          token: ${{ secrets.GH_PAT }}
          path: java-app

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Java App
        run: |
          cd java-app
          mvn clean package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build & Push Docker Image
        run: |
          cd java-app
          docker build -t manojandroid/social-service:${{ env.IMAGE_TAG }} .
          docker push manojandroid/social-service:${{ env.IMAGE_TAG }}
